describe('Admin', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/docs')
    cy.get('.opblock-summary-description').contains('Get All Admins').click()
    cy.get('.try-out__btn').contains('Try it out').click()
    cy.get('.opblock-control__btn').contains('Execute').click()
  })
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/docs')
    cy.get('.opblock-summary-description').contains('Create Admin').click()
    cy.get('.try-out__btn').contains('Try it out').click()
    cy.get('input[placeholder="username"]').type('jadmin')
    cy.get('input[placeholder="password"]').type('jorge123')
    cy.get('.opblock-control__btn').contains('Execute').click()
  })
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/docs')
    cy.get('.opblock-summary-description').contains('Admin Change Password').click()
    cy.get('.try-out__btn').contains('Try it out').click()
    cy.get('input[placeholder="admin_user"]').type('jadmin')
    cy.get('input[placeholder="admin_password"]').type('jorge12345')
    cy.get('.opblock-control__btn').contains('Execute').click()
  })
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/docs')
    cy.get('.opblock-summary-description').contains('Delete Admin Account').click()
    cy.get('.try-out__btn').contains('Try it out').click()
    cy.get('input[placeholder="admin_name"]').type('jadmin')
    cy.get('.opblock-control__btn').contains('Execute').click()
  })
})